#-*- encoding:utf-8 -*-
#+title: docbook_files Notizen

* Jetzt

** DONE Detailausgabe gegenüber Hierarchie

Die Hierarchie ist die Hauptausgabe. Allerdings kann man sich über
'--details' auch die Detailangaben zu allen beteiligten Dateien
ausgeben lassen. Hier werden alle Angaben ausgegeben, die oben
optional sind.

Besonders wichtig ist die Zusammenfassung, also Dateien, die an
mehreren Stellen eingebunden werden, also mehrere Eltern haben!

Die Detailausgabe führt dann über zum Releasedokument.

** DONE Ausgabeformat YAML, JSON

Fehlerbehandlung vereinheitlichen, damit die Datenstruktur sinnvoller
wird.

** DONE Änderung Anzeige
*** Hierarchie

Nur der Hierarchiebaum, aber mit längeren Namen. Das heißt, die
Dateien werden mit Pfad angezeigt, mit relativem zum Masterdokument.

Falls zu lang am Anfang kürzen mit Ellipse.

URIs oder nicht relative Dateien werden mit dem Anfang angezeigt,
ggf. in der Mitte gekürzt.

*** Zusammenfassung

 * X Dateien
 * Y inkludierte DocBooks
 * Z referenzierte

YAML/JSON übernehmen und seinen eigenen machen.
*** Details

Die restlichen Angaben werden in die optionalen Details
verschoben. Die Optionen sind dann nicht mehr notwendig.

Wenn jemand den Bericht nicht mag, kann er gern die Daten über

** TODO Dateien mit mehreren Eltern

Besonders wichtig ist die Zusammenfassung, also Dateien, die an
mehreren Stellen eingebunden werden, also mehrere Eltern haben! Es geht
daher nur um das Parent-Element in FileData. Das muss ein Array
sein. Und bei der Ausgabe muss auch der qualifizierte Name angegeben
werden, derzeit ist es nur der reine Dateiname.

** DONE Behandlung von fehlerhaften XMLs verbessern
Zur Zeit gibt der Parser Fehlermeldungen aus, die aber ignoriert
werden. Auf Non-XML hinweisen.

Ist die Hauptdatei Non-XML, abbrechen.




* Später

** Waren das alle refs in DocBook?

** Was ist mit URLs?
Ignorieren oder gezielt verarbeiten? Wei häufig sind die?

** EXIF-Daten für Bilder?

** Metas für Video und Audio?

** Was ist mit DocBook Assemblies?


* Andere Baustelle?

** Releasedokument?

Die Ausgabe kann in einer Datei gespeichert werden, die dann als
Manifest für ein Archiv dienen kann. Anhand des Dokuments kann man
schauen, ob die vorliegenden Dateien dem gespeicherten Stand
entsprechen.

Gehört ein solches Dokument zur Kernfunktionalität?

** Signatur

Auf dem Manifest aufbauend die Sammlung oder einzelne Dokumente
signieren?

** Ausgabeformat Graphviz/HTML --> docbook_web
** Ausgabeformat RDF? Wofür?
** Zusammenhang mit SCM wie bei Bones?
